---
- hosts: all
  become: yes
  tasks:
    - name: install latest nginx
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: enable nginx
      service:
          name: nginx
          enabled: yes