---
- hosts: all
  become: yes
  tasks:
    - name: install latest nginx
      apt: name=nginx state=latest
    - name: enable nginx
      service:
          name: nginx
          enabled: yes
    - name: Copy nginx.conf
      template:
        src: "lb.conf"
        dest: "/etc/nginx/sites-enabled/lb.conf"
    - name: restart nginx
      service:
          name: nginx
          state: restarted
