---
- hosts: nodes
  become: yes
  gather_facts: yes
  tasks:
    - name: install latest apache2
      apt: name=apache2 state=latest
    - name: start apache2
      service:
          name: apache2
          state: started
    - name: enable apache2
      service:
          name: apache2
          enabled: yes
    - name: write in html file
      template: src=node.j2 dest=/var/www/html/index.html