---
- hosts: all
  become: yes
  tasks:
    - name: install latest apache2
      apt: name=apache2 state=latest
    - name: start apache2
      service:
          name: apache2
          state: started
    - name: enable apache2
      service:
          name: apache2
          enabled: yes