---
- hosts: all
  tasks:
    - name: install latest apache2
      apt: name=apache2 state=latest
    - name: start apache2
      service:
          name: apache2
          state: started
    - name: enable apache2
      service:
          name: apache2
          state: enabled
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts