---
- hosts: lb
  become: yes
  tasks:
    - name: install latest nginx
      apt: name=nginx state=latest
    - name: enable nginx
      service:
          name: nginx
          enabled: yes
    - name: Copy nginx.conf
      template:
        src: "lb.conf"
        dest: "/etc/nginx/sites-enabled/default"
    - name: restart nginx
      service:
          name: nginx
          state: restarted
- hosts: nodes
  become: yes
  gather_facts: yes
  tasks:
    - name: install nginx, fortunes and python3
      apt:
        pkg:
        - nginx
        - fortune
        - fortunes-off
        - python3
        - python3-pip
        - fcgiwrap
    # - name: enable module cgid
    #   shell: "a2enmod cgid"
    - name: create cgi-bin
      file:
        path: /usr/lib/cgi-bin
        state: directory
    - name: write in cgi python script
      template: 
        src: cgi.j2
        dest: /usr/lib/cgi-bin/script.py
        mode: "0755"
    - name: restart nginx
      service:
          name: nginx
          state: restarted
    - name: enable nginx
      service:
          name: nginx
          enabled: yes

